<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCfxatWo\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCfxatWo/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCfxatWo.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCfxatWo\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerCfxatWo\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'CfxatWo',
    'container.build_id' => '4900651f',
    'container.build_time' => 1614930912,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCfxatWo');
